### ISSUE TITLE
Ne fonctionne pas avec Google Chrome >= 58

### ISSUE THREAD

**Issue by papasax** [jleroy/MoloChrome#3]
Sous Mac os 10.12.15 
Seul le logo de la chaine est affiché. Pas de son, pas d'image.

**Comment by jleroy** [comment]
Il s'agît d'un problème connu.
Molotov utilise les Encrypted Media Extensions (EME) afin de protéger les contenus diffusés. Depuis Chrome 58, il n'est plus possible d'utiliser les EME sur une connexion non chiffrée (HTTP). 
L'interface app.molotov.tv n'étant pas disponible en HTTPS, le service ne fonctionne plus sous Chrome.

De mon côté, je ne peux rien faire pour contourner ça. L'équipe de Molotov est au courant du problème, mais aucune date de prévue pour le support du HTTPS.

Je laisse ce ticket ouvert pour les autres utilisateurs.

**Comment by jleroy** [comment]
L'interface app.molotov.tv est désormais disponible en HTTPS, MoloChrome fonctionne donc à nouveau avec les versions de Chrome >= 58.
