### ISSUE TITLE
Connexion

### ISSUE THREAD

**Issue by MJinxie** [jleroy/MoloChrome#5]
Bonjour,
Je viens d'installer l'application et cela fait 2h que "nous avons rencontré une erreur" quand je souhaite me connecter

**Comment by MJinxie** [comment]
Bonjour, toujours le même problème, je ne peux pas me connecter à mon compte

**Comment by jleroy** [comment]
Comme mentionné sur la [fiche de l'extension](https://chrome.google.com/webstore/detail/molochrome/ichlkljiijcjkpagcinkkbikamddbefn) sur le Chrome Web Store, MoloChrome n'est pas compatible avec les versions de Chrome >= 58. 

Le problème que tu rencontres n'est pas lié, mais même après correction de celui-ci l'extension ne sera de toute façon pas fonctionnelle. Du coup je n'ai pas prévu de corriger ça tant que Molotov ne supportera pas les dernières versions de Chrome.
